---
driver: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
- name: centos-6.5
- name: centos-5.10
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[opscode-ruby]
  attributes:
    opscode-ruby:
      rbenv_uid: 393
    versions:
    - 1.9.3-p484
    global: 1.9.3-p484
    base_gems:
    - bundler
    - mixlib-shellout
